### PR TITLE
Add RoboHome logo to upper left-hand corner

### PR DESCRIPTION
**Pull request by kailichiang**
## Description
Create a general partial.header file including Logo, text, and so on, which can be included in any blade template.

## Motivation and Context
Add RoboHome logo to upper left-hand corner of all pages #151 

## How Has This Been Tested?
Passed original laravel dusk test

## Screenshots (if appropriate):

- **Home**
home
- **Login**
login
- **Forget Password**
robohomeweb_forgetpassword
- **Reset Password**
robohomeweb_resetpassword
- **Devices**
devices

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement/Security (non-breaking change which is not noticeable to end users)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I created a feature branch and did not open a pull request from my `master` branch.
- [x] My code follows the code style of this project.
- [ ] My change requires an update to the README and I have updated it accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] This is a complete change and doesn't leave the project in a bad state.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by dbudwin** [comment]
So far this looks good.  I haven't had a chance to pull this code down and try it out for myself yet.  Would you mind editing your pull request description and adding a screenshot in the corresponding location in the description?

**Comment by kailichiang** [comment]
I added screenshots for each page. You can take a look.

**Comment by kailichiang** [comment]
Oops. This is actually a bug. I have fixed it and pushed by `fixup!`.  However, I'm not really familiar with `fixup!` so I can't assure if my code got updated.

The problem is at line 6 of the file `resources/views/partials/header.blade.php` the url should be `url(/images/RoboHome_24x24.svg)`. I missed the `/` before `image` in the previous version. You may pull my code for advanced check.

**Comment by dbudwin** [comment]
I don't believe your `fixup!` commit worked as intended (unless you already squashed the commits together.  No worries though, I will pull this down later and check it again.  Fixup commits usually work by making the changes locally and then staging your changes (`git commit add`) then running `git commit --fixup <commit sha of commit you want to change>`.  Then you do `git push --force-with-lease origin <branch with changes>`.

**Comment by kailichiang** [comment]
I added screenshots of `Forget password page` and `Reset password page`. 

For `fixup!`, I referred your suggested link, https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html, and did `git rebase -i --autosquash`. Probably I shouldn't do it.

**Comment by dbudwin** [comment]
Ah, yes.  So the normal flow would be you push your `fixup!` commit then I re-review the code.  I usually only look at the `fixup!` commit so I can see what changed between reviews.  Then, if the changes look good, I would approve the review and let you know now would be a good time to run that `--autosquash` command.  This takes the `fixup!` commit and makes it part of the underlying commit (almost as if you amended it).  I know `fixup!`'s aren't commonly used, but I prefer them because I think it makes reviewing iterations easier and also preserves a cleaner git history.  But for such a simple change like what you did here, it isn't an issue that you already squashed the commits together.

Also, if there was still an issue with the `fixup!` commit, you can `fixup!` the original `fixup!` commit.  Then squashing will still neatly organize all the `fixup!`'s into a single commit.  It's also possible to push multiple `fixup!` commits at once if you have multiple regular commits that need fixing.

**Pull request merged**
