### PR TITLE
added single place for device owner test

### PR DESCRIPTION
**Pull request by zhikiri**
what can be done after:
 - change the request parameter names
 - change the api controller actions
 - move logic from trait to separate service
 - use service in api and web

### CODE REVIEW

**Comment by zhikiri** [comment]
@dbudwin please, check the tests. 
In PR user existence is more strict

**Comment by dbudwin** [comment]
While this does create a single place for checking if a user owns the device, it doesn't remove some of the bulkiness I was alluding to in the issue description.  For example:

The `delete()` function in `Web/DevicesController` currently looks like this:

```
public function delete(Request $request, int $id): RedirectResponse
{
    $doesUserOwnDevice = $this->currentUser()->doesUserOwnDevice($id);

    if (!$doesUserOwnDevice) {
        $request->session()->flash(FlashMessageLevels::DANGER, 'Error deleting device!');

        return redirect()->route('devices');
    }

    $name = $this->deviceModel->find($id)->name;

    $this->deviceModel->destroy($id);

    $request->session()->flash(FlashMessageLevels::SUCCESS, "Device '$name' was successfully deleted!");

    return redirect()->route('devices');
}
```

Including, blank lines, that function is up to 8 lines longer than it needs to be.  It would be awesome if the above function could look like this:

```
public function __construct(Device $deviceModel, User $userModel, MessagePublisher $messagePublisher, IDeviceInformation $deviceInformation)
{
    ...

    $this->middleware('ownsDevice',  ['delete', 'update', 'handleControlRequest']);

    ...
}

public function delete(Request $request, int $id): RedirectResponse
{
    $name = $this->deviceModel->find($id)->name;

    $this->deviceModel->destroy($id);

    $request->session()->flash(FlashMessageLevels::SUCCESS, "Device '$name' was successfully deleted!");

    return redirect()->route('devices');
}
```

Now this doesn't have to be done using middleware, a trait is plausible too.  A similar implementation like my above suggestions would be needed for the API too.

**Comment by zhikiri** [comment]
That’s why you need to move your business logic to the services classes. To keep it in 1 place

**Comment by dbudwin** [comment]
Correct, that's what we're trying to accomplish. Is there a shortcoming with the suggestion above with middleware above you're hinting at that I'm not seeing?

**Comment by zhikiri** [comment]
Nope, it's a big infrastructure changes as I mentioned before (request parameter changes, move logic in to the service). I think it should affect all project codebase.

**Comment by dbudwin** [comment]
@zhikiri Are you planning on making additional commits to this?  I don't want the project to be in an intermediary state and would prefer to get most of the work done in a single PR.

**Comment by zhikiri** [comment]
@dbudwin let's define scope of this PR and I will finish it. It works for you ?

**Comment by dbudwin** [comment]
@zhikiri Cool!  There is now a Slack channel if you think it'd be quicker to discuss there: https://robohome-slackin.herokuapp.com/

On the top of my head, this PR should:

1. Reduce the amount of bulkiness in functions that need to check if a user owns a device
2. Not contain todo messages or comments about future work or things that aren't in a suitable state for delivery
3. Contain tests around new functionality and tweak existing tests to match the new architecture

The goal of this PR necessarily be that there is only a single place to check if a user owns a device, it's to remove the redundancy of having the same code in many functions that checks if a user owns a device.  This is why I think middleware is a good and easy option to fix this problem.

Thoughts?

**Comment by zhikiri** [comment]
@dbudwin okay, let's make it in this way

**Comment by zhikiri** [comment]
@dbudwin don't have time for this task now, sorry

**Pull request closed without merging**
