### PR TITLE
Add logos and logo file

### PR DESCRIPTION
**Pull request by EdenSG**
Notes:
- I've put the favicon in the root of the public directory, because that's where browsers look by default
- I decided on "assets" instead of "images" for the new directory in the root of the repo, because I feel it's more open-ended about what goes inside (i.e. any other design assets could end up there too)
- I've included a bunch of different styles (png and svg). We'll want to use the svg versions whenever possible.
- Colour: I haven't done anything colour-wise. If you'd like to pick a colour, it'll be very easy to theme these icons, however, since they're just black at the moment.

### CODE REVIEW

**Comment by EdenSG** [comment]
Closes #103

**Comment by dbudwin** [comment]
I pulled this down and looked over it.  Looks really sharp!  One quick question, I noticed that the RoboHome_24x24.svg has some padding around it that the RoboHome_16x16.svg doesn't.  Is there a particular reason for this?  This is also true for the png versions of RoboHome_24x24.

screen shot 2017-10-02 at 22 33 05

**Comment by EdenSG** [comment]
Yes, that's so that they're pixel perfect at their respective sizes. I took the house shape from Google's Material Design Icons to create the 24x24 version, and when I then downsized it to 16x16 I moved points around to keep things within the pixel grid as much as possible. That meant changing the proportions a little (since there's a 2/3 scale down), and in order to keep the proportions close I used the extra padding.

Just noticed that the top of the house is 1px too high in the 16x16px version though. I'll fix that.

**Comment by dbudwin** [comment]
Looks good.  If you don't mind squashing your two commits together, I'll go ahead and merge it (there's no need to have the files that are one pixel off in the commit history)!  Note, I may merge something else in the meantime and you'll need to rebase.

**Comment by EdenSG** [comment]
Sure sure

**Comment by dbudwin** [comment]
I'm done merging other PRs and I'm really looking forward to this!  It's ready for rebasing whenever you have a minute.

**Comment by dbudwin** [comment]
Great work!  Thank you very much.  I hope you'll continue to be a part of this project :)

artistsquirrel

**Pull request merged**
